define oliver = Character("Салатик Оливер")
define hamayumi = Character("Хамаюми", what_prefix="«", what_suffix="»")
define nurse = Character("мед")
define q = Character("Quins") 
define n = Character("Nighstess")
define a = Character("MR_artemka")
define z = Character("SeryogaZOMbi")
define p = Character("Песок Песочнеков")
